// Start Vite and sim/server.py first. Exercises the real superstore without paid calls or applying changes.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
const base = process.env.DEMO_BASE_URL ?? 'http://127.0.0.1:5175';
const output = process.env.DEMO_OUTPUT_DIR ?? '/tmp/eathack-demo';
const runId = 'run_20261003_142844_s22_mock_483c', code = '20969929';
const run = JSON.parse(await readFile(new URL(`../public/data/runs/${runId}.json`, import.meta.url)));
const events = run.agents.flatMap(a => a.events).filter(e => e.product === code && e.mechanism !== 'error');
const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH } : {}), args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
await mkdir(output, { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
page.setDefaultTimeout(20000);
const errors = [], requests = [];
page.on('pageerror', e => errors.push(e.message));
page.on('request', r => { if (r.method() === 'POST') requests.push({ url: r.url(), body: r.postDataJSON() }); });
try {
  await page.goto(`${base}/?store=superstore&nointro&view=analytics&run=${runId}&product=${code}`);
  const overview = page.getByRole('complementary', { name: /product analytics/ });
  await overview.waitFor({ timeout: 60000 });
  assert.match(await overview.innerText(), /Medaglioni ai funghi/);
  const ranking = overview.locator('.rk-head');
  assert.equal(await ranking.getAttribute('aria-expanded'), 'false');
  await ranking.click();
  assert.equal(await overview.locator('.rk-cols .rk-row').count(), 20);
  await ranking.click();
  const handled = e => typeof e.picked_up === 'boolean' ? e.picked_up : e.stage_reached ? ['put_back', 'taken'].includes(e.stage_reached) : e.noticed && ['pick', 'reject'].includes(e.decision);
  assert.deepEqual((await overview.locator('.ins-funnel-row > b').allTextContents()).map(Number), [events.length, events.filter(e => e.noticed).length, events.filter(handled).length, events.filter(e => e.decision === 'pick').length]);
  const shelf = page.getByRole('region', { name: 'shelf rearrangement preview' });
  await shelf.getByRole('button', { name: /see shelf moves/ }).waitFor({ timeout: 60000 });
  const forecast = await shelf.locator('.ins-shelf-chart').getAttribute('aria-label');
  await page.screenshot({ path: `${output}/superstore-overview.png` });
  await overview.getByRole('button', { name: 'view shopper activity', exact: true }).click();
  const log = page.getByRole('table', { name: 'shopper activity log' });
  await log.waitFor();
  assert.equal(await log.locator('tbody tr').count(), Math.min(events.length, 20));
  await page.getByRole('button', { name: 'next', exact: true }).click();
  assert.equal(await log.locator('tbody tr').count(), events.length - 20);
  await page.getByRole('combobox', { name: 'filter shopper outcome' }).selectOption('pick');
  assert.equal(await log.locator('tbody tr').count(), events.filter(e => e.decision === 'pick').length);
  const downloading = page.waitForEvent('download');
  await page.getByRole('button', { name: 'download csv', exact: true }).click();
  const csv = await readFile(await (await downloading).path(), 'utf8');
  assert.match(csv.split('\n')[0], /step/);
  assert.equal(csv.trim().split('\n').length - 1, events.filter(e => e.decision === 'pick').length);
  await log.getByRole('button', { name: /open decision trace/ }).first().click();
  await page.getByRole('complementary', { name: 'decision trace' }).waitFor();
  await page.getByRole('button', { name: '← back', exact: true }).click();
  await overview.waitFor();
  assert.match(await overview.innerText(), /Medaglioni ai funghi/);
  await overview.evaluate(e => e.scrollTop = 0);
  await shelf.getByRole('button', { name: /see shelf moves/ }).click();
  const rearrange = page.getByRole('complementary', { name: 'rearrange the shelves' });
  await rearrange.locator('.ra-cat.on').waitFor({ timeout: 120000 });
  assert.match(await rearrange.locator('.ra-cat.on').innerText(), /chilled pizza pasta pies/i);
  const expectation = forecast.match(/current ([\d.]+), proposed ([\d.]+)/);
  const why = await rearrange.locator('.ra-why-sub').innerText();
  assert.ok(why.includes(`${expectation[1]} → ${expectation[2]}`), `forecast mismatch: ${forecast} / ${why}`);
  assert.ok(await rearrange.locator('.ra-steps li').count() <= 3);
  await rearrange.getByRole('button', { name: '▶ watch it', exact: true }).click();
  await rearrange.getByRole('button', { name: '↺ put it back', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/superstore-moves.png` });
  await page.getByRole('button', { name: 'analytics', exact: true }).click();
  await overview.waitFor();
  await page.getByRole('button', { name: /switch product:/ }).click();
  await page.getByRole('combobox', { name: 'search switch product' }).fill('cream of tomato');
  await page.getByRole('option').first().click();
  assert.match(await overview.innerText(), /Cream of Tomato Soup/i);
  assert.equal(await page.getByRole('table', { name: 'shopper activity log' }).count(), 0);
  await page.setViewportSize({ width: 1280, height: 800 });
  const size = await overview.evaluate(e => ({ width: e.clientWidth, scroll: e.scrollWidth, right: e.getBoundingClientRect().right }));
  assert.ok(size.scroll <= size.width + 1 && size.right <= 1280, JSON.stringify(size));
  await page.screenshot({ path: `${output}/superstore-1280.png` });
  await page.getByRole('button', { name: 'watch', exact: true }).click();
  await page.getByRole('list', { name: 'leaderboard' }).getByRole('listitem').first().click();
  const productPanel = page.getByRole('complementary', { name: /^product / });
  await productPanel.waitFor();
  const selectedName = await productPanel.getAttribute('aria-label');
  await productPanel.getByRole('button', { name: 'view product analytics →', exact: true }).click();
  await overview.waitFor();
  assert.equal(await overview.getAttribute('aria-label'), selectedName.replace('product ', 'product analytics for '));
  await page.route('**/api/rearrange/suggest', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'offline' }) }));
  await page.reload();
  await page.getByText('shelf suggestions are unavailable.', { exact: false }).waitFor();
  assert.equal(await page.locator('.ins-funnel-row').count(), 4);
  await page.getByRole('button', { name: 'retry shelf suggestion' }).click();
  await page.getByText('shelf suggestions are unavailable.', { exact: false }).waitFor();
  assert.ok(requests.every(r => !/\/api\/(run|agent_run|interview|rearrange\/validate)/.test(r.url)), 'unexpected model or validation calls');
  assert.ok(requests.filter(r => r.url.includes('/rearrange/suggest')).every(r => r.body.store === 'superstore' && r.body.run_ids[0] === runId));
  assert.deepEqual(errors, []);
  console.log(`PASS: superstore funnel, activity pagination/filter/CSV, trace return, matching 3D forecast, animation, product switching, desktop fit and unavailable API. Screenshots: ${output}`);
} finally { await browser.close(); }
